global:
  scrape_interval: 15s      # Récupère les métriques toutes les 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'mon-application'
    static_configs:
      - targets: ['app:5000']  # Notre application Flask